### ISSUE TITLE
Timeline for dropping deprecated "p-*" phosphor-based selectors?

### ISSUE THREAD

**Issue by nmichaud** [jupyterlab/lumino#106]
I've noticed that dragging tabs in the TabBar widget feels much laggier than before. I narrowed the culprit down to the merge that migrated the CSS selectors to new 'lm-*' based prefixes (https://github.com/jupyterlab/lumino/pull/20) while keeping the original ones. Chrome seems to have some issues when an element has two different selectors with identical stylesheets. Is there a timeline to remove the deprecated selectors from the codebase? I assume JupyterLab has fully migrated over by now.

**Comment by jasongrout** [comment]
An update: JLab 3 still has the phosphor compatibility shim, and the hope is to remove it in JLab 4 (planned release at the end of this year) to fully migrate to Lumino with no backwards compatibility for Phosphor.

> Chrome seems to have some issues when an element has two different selectors with identical stylesheets.

Interesting. I haven't noticed a lag. Do you have a reference link or Chrome bug report for problem?

**Comment by nmichaud** [comment]
> > Chrome seems to have some issues when an element has two different selectors with identical stylesheets.
> 
> Interesting. I haven't noticed a lag. Do you have a reference link or Chrome bug report for problem?

Sorry that was a red herring. Turns out it was this issue - #128. Removing all the phosphor based selectors ended up fixing the problem but hid what the underlying problem was.

**Comment by jasongrout** [comment]
Thanks for following up.
