### ISSUE TITLE
Question: correct way of removing a widget from a layout?

### ISSUE THREAD

**Issue by piersdeseilligny** [jupyterlab/lumino#141]
Hi,
I've got a fairly complex layout, which involves adding and removing TabBars from a SplitLayout dynamically - however I can't figure out the correct way of removing and disposing all TabBars from the layout. I've tried
```js
      each(splitpanel.widgets, (child,i)=>{
        (child as TabBar<Widget>).dispose();
      });
```
which looks like this:
[![Image from Gyazo](https://i.gyazo.com/8b78227805321b3b84dfd1762029cb55.gif)](https://gyazo.com/8b78227805321b3b84dfd1762029cb55)

the tab bars don't seem to get removed from the layout. Apparently, from setting the TabBar parent to `null` in the dispose function (which doesn't seem to actually remove it from the SplitPanel??).

The desired behaviour can be achieved by using `.hide()` instead of `.dispose()`:
[![Image from Gyazo](https://i.gyazo.com/96d4f2e180abebead54a55b4ed210609.gif)](https://gyazo.com/96d4f2e180abebead54a55b4ed210609)

Although this looks correct, I obviously don't want to use it seeing as the old TabBars remain in the dom, even when they should be long gone.

Am I just misunderstanding what `dispose` is supposed to be doing? What's the 'correct' way of permanently removing widgets from a layout?

**Comment by jasongrout** [comment]
If you can post a minimal example reproducing the issue, that will help us be able to diagnose what might be going on.

In general, setting the parent to `null` should be enough to remove a widget from the parent layout, and dispose should be doing that, as you mention.

**Comment by piersdeseilligny** [comment]
Turns out it was a stupid mistake - it's impossible to use 
```ts
each(splitpanel.widgets, (child,i)=>{
  (child as TabBar<Widget>).dispose();
});
```
to clear all widgets from a panel, because you're removing items from the array while you're iterating over it. 
Instead, I used
```ts
while(main.widgets.length>0){
  main.widgets[main.widgets.length-1].dispose();
}
```
which works as expected.
