### ISSUE TITLE
Datagrid's SectionResizeRequest

### ISSUE THREAD

**Issue by martinRenou** [jupyterlab/lumino#147]
The datagrid's `SectionResizeRequest` is nowhere to be found in the codebase but when it's defined: https://github.com/jupyterlab/lumino/search?q=SectionResizeRequest and https://github.com/jupyterlab/lumino/search?q=section-resize-request. Could it be a leftover from old implementations?

Happy to open a PR if that's the case.

**Comment by martinRenou** [comment]
I am currently looking for the replacement of this message, if somebody has a hint for me that would be great :)

**Comment by martinRenou** [comment]
I guess `ColumnResizeRequest` and `RowResizeRequest` are the replacements.

**Comment by blink1073** [comment]
> I guess ColumnResizeRequest and RowResizeRequest are the replacements.

That sounds correct to me
