### ISSUE TITLE
Menu at the end of the screen renders outside

### ISSUE THREAD

**Issue by hbcarlos** [jupyterlab/lumino#207]
I'm not sure if this is a bug or not.

### Problem
The lumino Menu has an option in its method `open` to force the position of the menu. The problem is that this option is activated by default when the MenuBar calls this method on one of its child menus.

See: https://github.com/jupyterlab/lumino/blob/a105b6f62d7e630ec2bc0095507fc7547ba29629/packages/widgets/src/menubar.ts#L602

This makes the menu to render outside the viewport when positioning the menu at the right part of the screen.
See the top-right menu on the following image:
![bad-menu](https://user-images.githubusercontent.com/26092748/126659157-7f420742-5b44-4da2-a11c-6bb0ead7f416.png)

After removing the option force:
![solved](https://user-images.githubusercontent.com/26092748/126659165-1048ec64-abdd-49f1-815b-e3e31085ffcd.png)

### Proposed Solution
Can we add an option on the constructor of the `MenuBar` to configure this when creating a new menubar?
Here: 
https://github.com/hbcarlos/lumino/blob/a105b6f62d7e630ec2bc0095507fc7547ba29629/packages/widgets/src/menubar.ts#L710

**Comment by fcollonval** [comment]
I did something similar for the `ContextMenu` in https://github.com/jupyterlab/lumino/pull/203/files#diff-3d07da50d2685605691ccf143d09bb0dcf713f3970255e6699c7fd3903d612cb

Don't hesitate to push a PR.

**Comment by hbcarlos** [comment]
Thx Frédéric!! Opening a PR right now.

**Comment by krassowski** [comment]
Can we close this one?

**Comment by hbcarlos** [comment]
Yes, sorry. I forgot!
