### ISSUE TITLE
Yarn v NPM (if wanted)

### ISSUE THREAD

**Issue by GordonSmith** [jupyterlab/lumino#22]
Not sure if jupyterlab has any preferences for Yarn over NPM - But if there is any interest in switching to NPM I have a working branch for NPM (it uncovered a few missing dependencies - which I will try and issue a PR for either-way).

**Comment by blink1073** [comment]
Hi @GordonSmith, does your NPM branch include any sharing of dependencies (e.g. lerna hoisting)?  We had used lerna for hoisting and found it to be brittle.  While we do have to be more careful about dependencies (as evidenced by your PR), yarn workspaces have been working well for us.

**Comment by GordonSmith** [comment]
Yes by default it uses the lerna "--hoist" option and disables the useWorkspaces feature.

FWIW I have been using lerna for quite a while and prefer the hoisted dependencies purely for the initial speed of installation, IMO the "brittleness" has gone.

If your already using yarn I don't see any reason to change, but if all your repos are on NPM and this one doesn't fit then now would be a good time to change (which is why I opened an issue and not a PR).

**Comment by jasongrout** [comment]
> If your already using yarn I don't see any reason to change, but if all your repos are on NPM and this one doesn't fit then now would be a good time to change (which is why I opened an issue and not a PR).

Right now, JupyterLab also uses yarn (but it also bundles yarn), so it it slightly simpler for me to keep using yarn.
