### ISSUE TITLE
Better tag release numbers

### ISSUE THREAD

**Issue by SnarkBoojum** [jupyterlab/lumino#235]
I notice the last version is tagged v2021.8.23 ; so it doesn't really conform to the usual vYYYY.MM.DD format, easily recognized and sorted by tools.

That means a version v2021.10.30 will not appear as newer than that one. A v2021.9.9 release would be the last of 2021 -- and with a v21.9.9... only my unborn grandchildren will see the next version!

Can you please add a v2021.08.23 tag and be more careful with next version numbers? Thanks!

**Comment by blink1073** [comment]
The git tags are generated from the package version, and `2021.08.23` is not a valid npm version.  Git supports listing tags by [creation date](https://stackoverflow.com/a/6270112).

**Comment by SnarkBoojum** [comment]
I'll get around that ; thanks!
