### ISSUE TITLE
[PATCH] MediaStreamErrorEvent removed from TypeScript from 4.4 onward

### ISSUE THREAD

**Issue by SnarkBoojum** [jupyterlab/lumino#236]
I'm trying to package lumino v2021.8.23 into Debian, and the compilation of virtualdom fails with the above error message.

**Comment by SnarkBoojum** [comment]
Relevant link discussing making some things obsolete -- including MediaStreamEventError: https://github.com/microsoft/TypeScript-DOM-lib-generator/issues/1029

Relevant link to a project with a similar problem: https://github.com/basst314/ngx-webcam/issues/130

**Comment by SnarkBoojum** [comment]
It looks like a trivial:
```
--- lumino.orig/packages/virtualdom/src/index.ts
+++ lumino/packages/virtualdom/src/index.ts
@@ -569,7 +569,7 @@
   ondrop: DragEvent;
   ondurationchange: Event;
   onemptied: Event;
-  onended: MediaStreamErrorEvent;
+  onended: ErrorEvent;
   onerror: ErrorEvent;
   onfocus: FocusEvent;
   oninput: Event;
--- lumino.orig/review/api/virtualdom.api.md
+++ lumino/review/api/virtualdom.api.md
@@ -52,7 +52,7 @@
     ondrop: DragEvent;
     ondurationchange: Event;
     onemptied: Event;
-    onended: MediaStreamErrorEvent;
+    onended: ErrorEvent;
     onerror: ErrorEvent;
     onfocus: FocusEvent;
     oninput: Event;
```
would be enough to get rid of this issue.

**Comment by blink1073** [comment]
Thanks @SnarkBoojum!  I think this should help with https://github.com/jupyterlab/jupyterlab/pull/10993 as well.  Mind submitting a PR?

**Comment by SnarkBoojum** [comment]
I have no clue how one does a PR, and for a two-line change, that looks overkill...
