### ISSUE TITLE
Why in `Layout`, `onUpdateRequest` is sending resizing message

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/lumino#260]
At https://github.com/jupyterlab/lumino/blob/5cccb087b074f1713d5c94bd8517b20f18a0e1fa/packages/widgets/src/layout.ts#L279-L283

Is there a reason to transform a update message to a resize message in `Layout`? It looks like a bug for me. In JupyterLab, I'm calling the `update` method of a toolbar with `ReactWidget` items. It results in items not being rendered.

**Comment by jasongrout** [comment]
Here is where Chris talks through the logic of that function: https://youtu.be/YfjnM3tRuuM?t=1430

**Comment by jasongrout** [comment]
Essentially, IIRC, updates events are not supposed to be propagated to child widgets. An update to a widget will cause that widget's layout to update its layout, which requires the children to possibly need to resize themselves.

**Comment by fcollonval** [comment]
Thanks @jasongrout - I need to figure out what am I doing wrong in https://github.com/jupyterlab/jupyterlab/pull/11369 so that `ReactWidget` is correctly mount into the DOM.
