### ISSUE TITLE
Debounce/Throttle an input text

### ISSUE THREAD

**Issue by echarles** [jupyterlab/lumino#289]
I have tried to use the `Throttler` class to limit the calls of a function when the user was typing in a input text.

This has a few use cases in jupyterlab (like limit the search or filter): instead of triggering a heavy call on each character typing, the idea is to trigger that heavy call every e.g. 0,5 second.

I have taken inspiration from https://github.com/jupyterlab/lumino/blob/66b9df5ecc8f22e203a96df8a252956e8c8a9263/packages/polling/tests/src/ratelimiter.spec.ts#L88-L102 and also looked at the current usage in JupyterLab, but was not able to make it work.

Instead of describing the various promise, await, void and phases... I have setup a codesandbox with a simple example. There may be things to fix in that codesandbox (feel free to jump there :))

https://codesandbox.io/s/lumino-rate-limiter-example-2wkqo?file=/src/index.ts

Related:

https://github.com/jupyterlab/lumino/issues/51
https://github.com/jupyterlab/lumino/issues/47

cc/ @afshin @jasongrout

**Comment by echarles** [comment]
I have updated the codesandbox with a simple vanilla implementation for a debounce.

![Untitled](https://user-images.githubusercontent.com/226720/150792192-d4ced244-bab9-452b-b0dd-a580a8c33278.gif)

**Comment by afshin** [comment]
```typescript
const debouncer = new Debouncer(showInputValueLumino, 1000);
input?.addEventListener("keydown", (e: KeyboardEvent) => {
  event = e;
  // For usage, see https://github.com/jupyterlab/lumino/blob/66b9df5ecc8f22e203a96df8a252956e8c8a9263/packages/polling/tests/src/ratelimiter.spec.ts#L88-L102
  // await does not help here.
  debouncer.invoke();
});
```

**Comment by afshin** [comment]
@echarles, when I modified your example as the above comment shows, it works as intentended.

**Comment by echarles** [comment]
Works great. Thx @afshin.

Closing.
