### ISSUE TITLE
src/graphicscontext.ts(243,7): error TS2322: Type 'string' is not assignable to type 'GlobalCompositeOperation'.

### ISSUE THREAD

**Issue by SnarkBoojum** [jupyterlab/lumino#298]
Compiling datadrid with a recent typescript leads to:
```
src/graphicscontext.ts(243,7): error TS2322: Type 'string' is not assignable to type 'GlobalCompositeOperation'.
```

So I guess there's again a stricter typing in typescript breaking parts of lumino.

By recent version of typescript, I mean 4.6.3.

**Comment by SnarkBoojum** [comment]
I dug a little, and I think the reason is that they tightened things in typescript so the type wouldn't be the same depending on the given string -- and for an unknown string, that means an error : [see here](https://github.com/microsoft/TypeScript-DOM-lib-generator/pull/1206)

**Comment by SnarkBoojum** [comment]
This looks like a trivial fix:
```
-  get globalCompositeOperation(): string {
+  get globalCompositeOperation(): GlobalCompositeOperation {
     return this._context.globalCompositeOperation;
   }
 
-  set globalCompositeOperation(value: string) {
+  set globalCompositeOperation(value: GlobalCompositeOperation) {
```

**Comment by vidartf** [comment]
Did you want to open a PR with your proposed changes (so credit can be attributed in commit log etc), or are you hoping someone else can code this up?

**Comment by vidartf** [comment]
PS: It is also worth noting what the proposed change would do to the minimally required TS version.

**Comment by blink1073** [comment]
I see your commit in the history: https://github.com/graph-algorithms/edge-addition-planarity-suite/commit/c03109f691988974c19e2d7115588dfead306912
