### ISSUE TITLE
Add `.min.js` versions to each package's build

### ISSUE THREAD

**Issue by afshin** [jupyterlab/lumino#344]
The `package.json` entries for `jsdelivr` and `unpkg` currently reference `dist/index.min.js` which no longer exists after updating many of the `devDependencies` and support needs to be re-added.

**Comment by 3coins** [comment]
@afshin I can look into this. Can you assign this to me.

**Comment by 3coins** [comment]
@afshin I just installed and ran `yarn build:dist` which generated the `dist/index.min.js` files inside individual packages. Is there anything more expected here?

**Comment by blink1073** [comment]
I can also verify that https://unpkg.com/@lumino/widgets@1.34.0/dist/index.min.js is a valid url.

**Comment by afshin** [comment]
I thought that I had broken this for Lumino 2, but I guess that means this
is not an issue. Thanks for checking it out!
