### ISSUE TITLE
Remove GitHub Pages version of docs

### ISSUE THREAD

**Issue by gabalafou** [jupyterlab/lumino#358]
I'm not sure if we want to remove the GitHub Pages docs at https://jupyterlab.github.io/lumino/, but I created this issue to track the decision either way (keep or remove).

**Comment by fcollonval** [comment]
:+1: to avoid providing multiple website - better to only have read the doc

**Comment by fcollonval** [comment]
I went ahead a suppress the website as well as the gh-pages branch
