### ISSUE TITLE
Should we compile to ES2018 in Lumino 2?

### ISSUE THREAD

**Issue by afshin** [jupyterlab/lumino#387]
It seems as though the browsers we support all support ES2018: https://caniuse.com/?search=ES2018

I propose switching to `ES2018` as our compilation `target`:

https://github.com/jupyterlab/lumino/blob/b603dd37d8d9586533d076bdaf225d2b105922fb/tsconfigbase.json#L21

What do you think?

## Pathological case
Out of curiosity, I looked to see how the `[Symbol.asyncIterator]` function in `Poll` compiled.

### TypeScript source
```typescript
async *[Symbol.asyncIterator](): AsyncIterableIterator<IPoll.State<T, U, V>> {
  while (!this.isDisposed) {
    yield this.state;
    await this.tick.catch(() => undefined);
  }
}
```

### Compiled with ES6 target
```javascript
[Symbol.asyncIterator]() {
  return __asyncGenerator(this, arguments, function* _a() {
      while (!this.isDisposed) {
          yield yield __await(this.state);
          yield __await(this.tick.catch(() => undefined));
      }
  });
```

### Compiled with ES2018 target
```javascript
async *[Symbol.asyncIterator]() {
  while (!this.isDisposed) {
      yield this.state;
      await this.tick.catch(() => undefined);
  }
}
```

---

This case is particularly egregious but all uses of `await` are wrapped in the ES6 version and native in the ES2018 version. We use `await` extensively in the `@lumino/application` and `@lumino/polling` packages.

---

Please 👍 if you agree and 👎 if you disagree.

**Comment by blink1073** [comment]
Looking at the ECMAScript 2016+ [compatibility table](https://kangax.github.io/compat-table/es2016plus/), it looks like among the browsers we support, async generators are available (and most other ECMAScript features to that point as well).  The only limitation I see is that Safari is missing support for [RegExp Lookbehind Assertions](https://github.com/tc39/proposal-regexp-lookbehind).
