### ISSUE TITLE
Change RTD `stable` to show Lumino 1.x docs until Lumino 2 final

### ISSUE THREAD

**Issue by afshin** [jupyterlab/lumino#412]
The `stable` RTD page for Lumino is showing alpha releases of Lumino 2 instead of the current stable 1.x line.

<img width="1086" alt="Screen Shot 2022-09-14 at 16 00 31" src="https://user-images.githubusercontent.com/159529/190190971-f2fa244a-b233-4310-a517-dce11f7ffd84.png">

**Comment by fcollonval** [comment]
This is due to the tag that was not presenting a prerelease structure.

When doing prerelease, we need to set a fake version with `year.month.day<prerelease>`. I did that for the latest alpha and it was ignored by RTD for stable.

**Comment by fcollonval** [comment]
Fixed by the latest release of 1.x branch
