### ISSUE TITLE
Only the first connected slot on a Signal is invoked

### ISSUE THREAD

**Issue by ajbozarth** [jupyterlab/lumino#42]
I'm not sure if this is an issue with how Signals work or with the specific callback function I'm running into. 

When the `_tabCloseRequested` Signal in `tabbar.ts` is emitted (on line 790) it only handles the the `_onTabCloseRequested` slot that is connected on line 77 of `tabpanel.ts`, any slots connect later, such as in an extension are no invoked. Specifically in the `Private.emit` function in `signaling/src/index.ts` on line 565, after on return from `invokeSlot` (in my example it's the `_onTabCloseRequested` slot) the value of `signal` for every `connection` in the `receivers` array is set to `null`.

As far as I have been able to stack trace down into the call I have been unable to find where this happens. From my understanding of the codebase, somewhere the Signal that is being handled is being disposed, and thus on return from `invokeSlot` all references to it are now `null`.

This means that when extra slots are added to existing Signals in extensions they will return success on connection but never triggered on emission.

In order to more easily see this issue I have recreated a demo extension that show the issue: https://github.com/ajbozarth/demo-jl-ext

**Comment by vidartf** [comment]
Would it be possible for the demo to be lumino only, without any of the jupyterlab packages?

**Comment by vidartf** [comment]
The dockpanel example might be relevant: https://github.com/jupyterlab/lumino/tree/master/examples/example-dockpanel

**Comment by jasongrout** [comment]
Perhaps something is responding to the tab close request by disposing the document, which is cascading into disconnecting the rest of the signal handlers? If so, perhaps whatever is disposing the document should do so asynchronously so that the other signal handlers can run first?

**Comment by ajbozarth** [comment]
@vidartf I didn't know that existed, I took some time working in that and managed to really whittle down my example. You can add the following chunk of code at the end of the `main()` function in https://github.com/jupyterlab/lumino/tree/master/examples/example-dockpanel and recreate the issue.

```
  let dockPanel = new DockPanel();
  dockPanel.addWidget(new ContentWidget('Black'), { mode: 'split-bottom' });

  let myTabBar = dockPanel.tabBars().next();

  if (myTabBar) {
    let connect = myTabBar.tabCloseRequested.connect((sender, args) => {
      console.log('tabClose callback run');
    });
    console.log('tabClose calBack connected: ' + connect);
  }

  Widget.attach(dockPanel, document.body);
```

By adding that code it will put a tab at the bottom of the page. By looking at the console you'll see that the callback function successfully connects to the `tabCloseRequested` signal on page load. But when you close the tab you will not see the console log that is inside the callback function (ie the callback was not run).

**Comment by ajbozarth** [comment]
@jasongrout I'll look at the lumino code to see if I can track something like that down

**Comment by ajbozarth** [comment]
I forgot to click send on this comment this afternoon, so I'll comment it as is:

-----------------

Ok I have some update to this, as well as an even more streamlined example.

Add just to following to the end of `main()` instead and the callback will be added to the closing of any tab on the example.

```
  let myTabBar = dock.tabBars().next();

  if (myTabBar) {
    let connect = myTabBar.tabCloseRequested.connect((sender, args) => {
      console.log('tabClose callback run');
    });
    console.log('tabClose calBack connected: ' + connect);
  }
```

This more streamlined version has allowed me to more accurately trace the issue. Specifically the callback is successfully run as long as at least one tab in the section is still there, but if you close the last tab it doesn't run. This is because Widget.dispose() runs Signal.clearData()

**Comment by ajbozarth** [comment]
So I've spent most of the day doing intricate stack tracing and logging to trace exactly what's happening here. Essentially this is a really specific edge case and annoying as it is it is behaving exactly as it should imho. 

When a tab is closed on a tab bar a function called `_removeWidget()` in `dock panel.ts` is eventually run, in this function there is a check if the tab being closed is the last tab in the tab bar, if it's not it breaks and things work as I expected. But if it's the last tab in the tab bar it disposes of the tabbar itself, which then clears the signals related to it. This mean that the `tabCloseRequested` signal will be removed and further connections to it will never run when closing the final tab in a tab bar.

@jasongrout @vidartf if this makes sense to you and you agree this annoying edge case should be left as is feel free to close this issue.

**Comment by jasongrout** [comment]
> But if it's the last tab in the tab bar it disposes of the tabbar itself, which then clears the signals related to it.

Ah, makes sense. Perhaps that tab bar disposal should be done asynchronously, like `setTimeout(...,0)` or maybe even better a promise resolution, to allow other tab close request handlers to run?

**Comment by jasongrout** [comment]
That would complicate the logic to introduce asynchronicity, but at the same time it would make this corner case maybe a bit better?

**Comment by ajbozarth** [comment]
Now that I'm aware of this edge case I've discovered an easy work-around to it. Instead of connecting my callback to the `tabCloseRequested` signal I've instead attached it to the `disposed` signal. This work-around may be a little much if I wanted it to run on tab close for all tabs including the last one (since I'd have to attach it to both) but in my case the final tab was the one I wanted to catch to begin with.

As for the asynchronicity idea, I'm not sure it would be possible, or at least very difficult, since the line where the tabbar is disposed is deep in the call stack and much code after it requires it is disposed first.

**Comment by jasongrout** [comment]
> As for the asynchronicity idea, I'm not sure it would be possible, or at least very difficult, since the line where the tabbar is disposed is deep in the call stack and much code after it requires it is disposed first.

I agree it's difficult to think through the corner cases. To be clear, my suggestion was to consider putting all of these lines in a setTimeout or promise resolution so they are executed after the js frame has finished: https://github.com/jupyterlab/lumino/blob/9ea670f44c5c3a9310ce0855ec658f7ffff2acc2/packages/widgets/src/docklayout.ts#L651

It's great that you have a workaround, and I think you're right to argue that the current behavior is also correct, and simpler to reason about as well since it is all synchronous.

**Comment by jasongrout** [comment]
> @jasongrout @vidartf if this makes sense to you and you agree this annoying edge case should be left as is feel free to close this issue.

Sounds good.

**Comment by vidartf** [comment]
If someone wants to tweak this, I see two possible ways:
- Always fire all signals "in-flight" if an object is disposed when emitting, e.g. by copying the relevant data while in the emission process. This might have a long tail though, so it might not be straight forward.
- Have the dispose call in docklayout (https://github.com/jupyterlab/lumino/blob/9ea670f44c5c3a9310ce0855ec658f7ffff2acc2/packages/widgets/src/docklayout.ts#L651) be called in the next animation frame / timeout of 0 (whatever is the current pattern in the repo). Likely to be ok, but some care would have to be taken that we do not create other corner cases due to the changes in timing.

**Comment by vidartf** [comment]
(here is a pattern of delayed dispose)
https://github.com/jupyterlab/lumino/blob/9ea670f44c5c3a9310ce0855ec658f7ffff2acc2/packages/widgets/src/tabbar.ts#L816-L829
