### ISSUE TITLE
DockPanel inside a DockPanel

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/lumino#43]
Given the following layout (adapted from the [DockPanel example](https://github.com/jupyterlab/lumino/tree/master/examples/example-dockpanel)), where `dock2` is a second `DockPanel` added to the first one with:

```typescript
let dock2 = new DockPanel();
dock2.addWidget(g2);
dock2.addWidget(y2, { mode: 'split-right', ref: g2 });
dock2.id = 'dock2';
dock2.title.label = 'Dock 2';
dock.addWidget(dock2, { mode: 'split-bottom', ref: r1});
```

![image](https://user-images.githubusercontent.com/591645/72925678-66882600-3d53-11ea-82fe-1eaca38c694f.png)

Is is possible to have control on where the widgets of an inner DockPanel can be docked? For example to disallow dropping them outside of "Dock 2":

![inner-dockpanel](https://user-images.githubusercontent.com/591645/72925772-8b7c9900-3d53-11ea-82bb-371f1af6f20f.gif)

**Comment by jasongrout** [comment]
I think this is tricky because the mimetypes from the inner dockpanel match the accepted drops for the outer dockpanel. Perhaps there is a way to override those mimetypes for one or the other to make the inner and outer dockpanels incompatible with each other.

**Comment by jasongrout** [comment]
Yeah, this is the mimetype it is setting and accepting. If you customized that to be different for the inner and outer dockpanels, things might work: https://github.com/jupyterlab/lumino/blob/1beb8b36878dc0b1c4a75ab627b3938808eef0ca/packages/widgets/src/dockpanel.ts#L489

**Comment by jasongrout** [comment]
Perhaps that string should be a class parameter that can be changed for these sorts of issues?

**Comment by jtpio** [comment]
Yes that's a good point.

It should be possible to try a quick and dirty solution, for example by appending the DockPanel `id` to the mime data, which would prevent drops to a widget with a different id.

> Perhaps that string should be a class parameter that can be changed for these sorts of issues? It probably ought to be at least a variable so it can be referenced instead of typed out exactly three different places.

Or by adding the `source` to the `Drag` object here:

https://github.com/jupyterlab/lumino/blob/1beb8b36878dc0b1c4a75ab627b3938808eef0ca/packages/widgets/src/dockpanel.ts#L969-L973

And checking for the source here:

https://github.com/jupyterlab/lumino/blob/1beb8b36878dc0b1c4a75ab627b3938808eef0ca/packages/widgets/src/dockpanel.ts#L489

**Comment by afshin** [comment]
As I recall this used to be possible before the dock panel refactor that
laid out everything by calculation and left the children as sibling nodes
in the DOM. The explicit design constraint was that a dock panel should not
reside in another dock panel. The suggestions in this thread may work, but
I would suggest revisiting the user experience of an embedded dock panel,
when we were re-designing this component we came to the conclusion that
it's a use case that might lead to convoluted UX.

**Comment by jtpio** [comment]
Thanks @afshin for the extra context.

Maybe such behavior could still be enabled using an opt-in flag, to let users do something like this if they really want to.

I'll experiment with this and report back, at least to get a feeling of what it looks like from a UX perspective.

**Comment by dhirschfeld** [comment]
This functionality might be useful for e.g. variable viewers for the debugger

(though I'm not sure that is an actual improvement over just adding them to the main DockPanel)

**Comment by jtpio** [comment]
Reusing the example from above, and implementing the idea from https://github.com/jupyterlab/lumino/issues/43#issuecomment-580195457 and using the `source` field from the `Drag` object:

![dockpanel-source](https://user-images.githubusercontent.com/591645/73449189-e79e7900-4362-11ea-8ad8-7274cd2681a4.gif)
