### ISSUE TITLE
Drag image is rendered off-screen

### ISSUE THREAD

**Issue by MetRonnie** [jupyterlab/lumino#593]
## Description

Since 2.0.0, the "image" that moves with your mouse when you drag & drop is rendered off-screen instead of under your cursor.

## Reproduce

1. Create a DockPanel with a widget in it
2. Drag the widget tab around

## Expected behavior

An image of the widget's tab moves around with your cursor.

## Context

- Operating System and version: Windows 10
- Browser and version: Chrome 114.0.5735.110
- JupyterLab version: N/A
- `@lumino` version: 2.0.0

I think this was introduced in #502 which replaced
https://github.com/jupyterlab/lumino/blob/578b0a3dfc40ff585dc8ce559c8fb75214a8d4ab/packages/dragdrop/src/index.ts#L234-L235

with
https://github.com/jupyterlab/lumino/blob/60060576f0ded96fb2f6d9d3c46cc9f9ca5dd080/packages/dragdrop/src/index.ts#L234

and now it seems the fixed-position offset is incorrect. Setting
```css
top: 0;
left: 0;
```
sort of fixes it but the top left of the image is anchored to the cursor rather than where you dragged from.

**Comment by fcollonval** [comment]
Thanks for reporting!

I guess that setting [transform-origin](https://developer.mozilla.org/en-US/docs/Web/CSS/transform-origin) is the way to fix this.

cc @krassowski for input

@MetRonnie would you be willing to open a PR?
