### ISSUE TITLE
Is is OK to have Circular Dependency in typescript，since I found some in source code

### ISSUE THREAD

**Issue by tarjintor** [jupyterlab/lumino#63]
Hello,I am using jupyterlab alot and I wrote python most of time.

I need to write some plugin for jupyterlab so I am learning to use lumino now

Since there is little document for lumino, I tried to read source code to figure out how thing go.

I am ok for most part,but when I try to figure out dependencies in lumino/widgets, I found 

```
// widget.ts
import {
  Layout
} from './layout';
```

and
```
// layout.ts
import {
  Widget
} from './widget';
```
As far as I know,this is not OK in python,this is Circular Dependency

So is this ok in typescript?I am new user for typescript

**Comment by blink1073** [comment]
Hi @tarjintor, yes, sometimes we have found it necessary to have circular imports.

**Comment by tarjintor** [comment]
OK,no more questions,thanks
