### ISSUE TITLE
How to persistence SplitPanel and DockPanel?

### ISSUE THREAD

**Issue by yswang0927** [jupyterlab/lumino#650]
How to persistence SplitPanel split sizes and  DockPanel layout, and restore them?

**Comment by krassowski** [comment]
Hi @yswang0927 this PR in JupyterLab implements persistence of SplitPanel sizes and might answer your question: https://github.com/jupyterlab/jupyterlab/pull/14901#issue-1832932341

**Comment by yswang0927** [comment]
> Hi @yswang0927 this PR in JupyterLab implements persistence of SplitPanel sizes and might answer your question: [jupyterlab/jupyterlab#14901 (comment)](https://github.com/jupyterlab/jupyterlab/pull/14901#issue-1832932341)

Thank you @krassowski 🎉
