### ISSUE TITLE
Refactor the plugins handling out of the `Application`

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/lumino#697]
### Problem

The plugins are handled directly within the `Application`. This prevents the usage of plugins to initialize application attribute. The symptomatic case is the need to customize the service manager in JupyterLab.

Xref: 
- https://github.com/jupyterlab/jupyterlab/issues/15329
- https://github.com/jupyterlab/jupyterlab/pull/16141#issuecomment-2049120215

### Proposed Solution

Extracting the plugin resolver logic in its own class (because why should such great feat be hard linked to the Application). Once we get that the logic in index.js will be:

- Create the plugin resolver with all the plugins
- Provide that resolver to the lumino Application

> :warning: we will need to expose the resolver method in the Application to ensure backward compatibility

**Comment by jtpio** [comment]
Thanks @fcollonval for opening the issue :+1: 

Linking to https://github.com/jupyterlab/lumino/issues/586 as this may also help with this use case.

**Comment by jtpio** [comment]
@fcollonval just checking if you had plans to look into this yourself, or if other contributors could also start looking into it?

**Comment by fcollonval** [comment]
I started a branch. I hope to get a PR next week. Is it too late?

**Comment by jtpio** [comment]
OK great, thanks for starting this!

I just wanted to double check what the status on this was, to avoid double work in case someone would be interested in looking into this.
