### ISSUE TITLE
`control`/`super` aren't captured when `data-lm-suppress-shortcuts="true"`

### ISSUE THREAD

**Issue by EdsterG** [jupyterlab/lumino#713]
## Description

When `data-lm-suppress-shortcuts="true"` is set, `control`/`super` aren't captured in the element.

## Reproduce

Create a canvas with `data-lm-suppress-shortcuts="true"` and printout keyboard events.

## Expected behavior

`control`/`super` are forwarded to the element when `data-lm-suppress-shortcuts="true"` is set.

## Context

- Operating System and version: MacOS
- Browser and version: Brave/Firefox
- JupyterLab version: 4.2.4

**Comment by krassowski** [comment]
`super` is hard to capture in general, I am not quite sure if this is a lumino issue just yet. Does it work when running outside of JupyterLab/lumio? Note: 

> Some operating systems may intercept the key so it is never detected

From https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/metaKey

**Comment by EdsterG** [comment]
Thank you for the quick response! After digging around a bit, the problem wasn't in Lumino and was solved with an fix to WGLMakie.
