### ISSUE TITLE
right-click mouse suppression attribute

### ISSUE THREAD

**Issue by EdsterG** [jupyterlab/lumino#714]
### Problem

The problem is clearly described in https://github.com/jupyterlab/jupyterlab/issues/16619 with a video.

### Proposed Solution

Proposed solution is to add another attribute to suppress the right-click mouse event, see https://github.com/jupyterlab/jupyterlab/issues/16619#issuecomment-2258741457.

**Comment by krassowski** [comment]
Thank you for opening the issue! The context menu is implemented in JupyterLab and can be suppressed with `data-jp-suppress-context-menu`, see https://github.com/jupyterlab/jupyterlab/issues/16619#issuecomment-2260309856 - closing as not actionable.
