### ISSUE TITLE
Task: Test UMD Approach Against JupyterLab

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/lumino#72]
We need to test the effects of #40 against JupyterLab before making a release.

Any thoughts on how do to that cleanly?

Worst case it might entail a `yarn link` for all of the lumino packages.

**Comment by jasongrout** [comment]
That's essentially what we did when we were modifying and testing phosphor packages in the accessibility sprint. It worked well: https://github.com/diagram-codesprint/Web4AllHackathon2019/blob/master/Jupyter.md

**Comment by jasongrout** [comment]
We could always make an alpha release of lumino, though. That's probably cleaner.

**Comment by blink1073** [comment]
I published alpha versions and tested in JupyterLab.  Here's what it looks like to view the Lumino source from JupyterLab.  I'll open an issue to track handling of sourcemaps for original sources:

<img width="1121" alt="image" src="https://user-images.githubusercontent.com/2096628/82728994-a509ff00-9cb9-11ea-994f-9148171e8758.png">


Tests passed CI on my fork (other than the slow ones):
https://github.com/blink1073/jupyterlab/actions/runs/113157507
https://github.com/blink1073/jupyterlab/actions/runs/113157508
https://github.com/blink1073/jupyterlab/actions/runs/113157509

Proceeding with the final release.  Thanks again @GordonSmith!

**Comment by blink1073** [comment]
Done!  https://github.com/jupyterlab/lumino/blob/master/CHANGELOG.md#2020-05-23
