### ISSUE TITLE
DataGrid.resizeRow and column don't work?

### ISSUE THREAD

**Issue by jseabold** [jupyterlab/lumino#73]
I'm trying to update [this code](https://github.com/pbugnion/jupyterlab-sql) to use jupyterlab 2.1. It had previously been using phosphor/datagrid 0.1.6.

I have two failing tests that rely on `resizeRow` and `resizeColumn`, and stepping through them, it looks to me like the `resizeRow` doesn't actually do anything. I thought maybe it was just async and there was a race condition, but it doesn't seem like it. It passes a message along but the row section size never changes afaict. If I call the private method, it works as expected. What am I missing?

Am I not using them correctly? Here's an example that I updated from `resizeSection`.

https://github.com/jseabold/jupyterlab-sql/blob/support-v2/__tests__/src/services/dataGridExtensions/events.test.ts#L101

**Comment by dhirschfeld** [comment]
Sorry, I can't help with this question, but I wonder if you might get any useful info from the implementation in `jupyterlab-debugger` - https://github.com/jupyterlab/debugger/pull/391

**Comment by blink1073** [comment]
Hi @jseabold, I believe the issue you're seeing is that `resizeRow` results in a [`postMessage`](https://github.com/jupyterlab/lumino/blob/36f0a077d426e99d4f283b268e1f7027ecae4596/packages/datagrid/src/datagrid.ts#L1373).  Posted messages are handled asynchronously.  You can wait for the message to get processed by waiting for an animation frame.  We have a convenience way to that called [`framePromise`](https://github.com/jupyterlab/jupyterlab/blob/e9ea2d5a76a57589d652b313f179a84a7f0660bb/packages/notebook/test/default-toolbar.spec.ts#L56) in [`@jupyterlab/testutils`](https://github.com/jupyterlab/jupyterlab/blob/2832e63ed0fdbad013fc314594361669226a750c/testutils/src/index.ts#L178).

**Comment by jseabold** [comment]
@blink1073 perfect. Thanks for the pointer.

**Comment by blink1073** [comment]
👍🏼
