### ISSUE TITLE
[Critical Bug] Changes to `JSONObject` in coreutils@1.5.1 are breaking jupyterlab extension builds

### ISSUE THREAD

**Issue by telamonian** [jupyterlab/lumino#83]
If I try to build the latest master of [jupyter-fs](https://github.com/jpmorganchase/jupyter-fs):

```
git clone git@github.com:jpmorganchase/jupyter-fs.git
cd jupyter-fs
make js
```

I get the following error on the `tsc` (ie typescript compilation) step:

```
$ tsc
../node_modules/@jupyterlab/observables/lib/modeldb.d.ts:227:9 - error TS2416: Property 'changed' in type 'ObservableValue' is not assignable to the same property in base type 'IObservableValue'.
  Type 'ISignal<this, IChangedArgs>' is not assignable to type 'ISignal<IObservableValue, IChangedArgs>'.
    Type 'this' is not assignable to type 'IObservableValue'.
      Type 'ObservableValue' is not assignable to type 'IObservableValue'.
        The types returned by 'get()' are incompatible between these types.
          Type 'JSONValue' is not assignable to type 'PartialJSONValue'.
            Type 'JSONObject' is not assignable to type 'PartialJSONValue'.
              Type 'JSONObject' is not assignable to type 'string'.

227     get changed(): ISignal<this, ObservableValue.IChangedArgs>;
            ~~~~~~~

../node_modules/@jupyterlab/observables/lib/modeldb.d.ts:231:5 - error TS2416: Property 'get' in type 'ObservableValue' is not assignable to the same property in base type 'IObservableValue'.
  Type '() => JSONValue' is not assignable to type '() => PartialJSONValue'.

231     get(): JSONValue;
        ~~~


Found 2 errors.
```

This is definitely being caused by the latest release of `@lumino/coreutils`, since if I add a resolution to the previous `coreutils` to my `package.json`:

```
    "resolutions": {
        "@lumino/coreutils": "1.5.0"
    }
```

the build error is fixed.

I beleive the underlying cause is the [redefintion of `JSONObject`](https://github.com/jupyterlab/lumino/commit/36debf6f5e367dea8f4019e988b2d411f65bbf57#diff-a5ee7256fc82e758380d3477453ddc47R30) that was part of the 1.5.1 release.

@lumino/coreutils@1.5.0:

https://github.com/jupyterlab/lumino/blob/00ae44153f4362f9892624a22d21f486017d488f/packages/coreutils/src/json.ts#L26-L30

@lumino/coreutils@1.5.1:

https://github.com/jupyterlab/lumino/blob/36debf6f5e367dea8f4019e988b2d411f65bbf57/packages/coreutils/src/json.ts#L26-L30

Because this was a patch release of coretuils (1.5.0 => 1.5.1), you'll likely only see the bug if you delete your `yarn.lock` (or if start from a fresh build that never had one).

**Comment by telamonian** [comment]
pinging @blink1073 @GordonSmith

**Comment by blink1073** [comment]
Yeah we should revert that change and make a 1.5.2

**Comment by telamonian** [comment]
In his [commit message]() for the `typescript@3.9.2` upgrade, @GordonSmith implied that the change to `JSONObject` had to do with https://github.com/microsoft/TypeScript/pull/36696.

So it sounds like the revert will have include the entirety of 36debf6f5e367dea8f4019e988b2d411f65bbf57/the typescript 3.9 upgrade

**Comment by telamonian** [comment]
I've added a PR that reverts 36debf6 over at #84

**Comment by telamonian** [comment]
It would be nice if we could keep the typescript upgrade, so I've now also added a minimal PR (over at #85) that just reverts the changes to `JSONObject` while leaving the rest of 36debf6 intact. Mostly just to see if it will pass the CI tests
